/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as OtherSectionsRouteImport } from './routes/other-sections'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as HealingJourneyRouteImport } from './routes/healing-journey'
import { Route as EditHomepageRouteImport } from './routes/edit-homepage'
import { Route as EditFooterRouteImport } from './routes/edit-footer'
import { Route as EditCardsRouteImport } from './routes/edit-cards'
import { Route as DamageJourneyRouteImport } from './routes/damage-journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealingJourneyIndexRouteImport } from './routes/healing-journey.index'
import { Route as HealingJourneySlugRouteImport } from './routes/healing-journey.$slug'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherSectionsRoute = OtherSectionsRouteImport.update({
  id: '/other-sections',
  path: '/other-sections',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HealingJourneyRoute = HealingJourneyRouteImport.update({
  id: '/healing-journey',
  path: '/healing-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const EditHomepageRoute = EditHomepageRouteImport.update({
  id: '/edit-homepage',
  path: '/edit-homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const EditFooterRoute = EditFooterRouteImport.update({
  id: '/edit-footer',
  path: '/edit-footer',
  getParentRoute: () => rootRouteImport,
} as any)
const EditCardsRoute = EditCardsRouteImport.update({
  id: '/edit-cards',
  path: '/edit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageJourneyRoute = DamageJourneyRouteImport.update({
  id: '/damage-journey',
  path: '/damage-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealingJourneyIndexRoute = HealingJourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HealingJourneyRoute,
} as any)
const HealingJourneySlugRoute = HealingJourneySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HealingJourneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/damage-journey': typeof DamageJourneyRoute
  '/edit-cards': typeof EditCardsRoute
  '/edit-footer': typeof EditFooterRoute
  '/edit-homepage': typeof EditHomepageRoute
  '/healing-journey': typeof HealingJourneyRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/media': typeof MediaRoute
  '/other-sections': typeof OtherSectionsRoute
  '/preview': typeof PreviewRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/healing-journey/$slug': typeof HealingJourneySlugRoute
  '/healing-journey/': typeof HealingJourneyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/damage-journey': typeof DamageJourneyRoute
  '/edit-cards': typeof EditCardsRoute
  '/edit-footer': typeof EditFooterRoute
  '/edit-homepage': typeof EditHomepageRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/media': typeof MediaRoute
  '/other-sections': typeof OtherSectionsRoute
  '/preview': typeof PreviewRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/healing-journey/$slug': typeof HealingJourneySlugRoute
  '/healing-journey': typeof HealingJourneyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/damage-journey': typeof DamageJourneyRoute
  '/edit-cards': typeof EditCardsRoute
  '/edit-footer': typeof EditFooterRoute
  '/edit-homepage': typeof EditHomepageRoute
  '/healing-journey': typeof HealingJourneyRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/media': typeof MediaRoute
  '/other-sections': typeof OtherSectionsRoute
  '/preview': typeof PreviewRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/healing-journey/$slug': typeof HealingJourneySlugRoute
  '/healing-journey/': typeof HealingJourneyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/damage-journey'
    | '/edit-cards'
    | '/edit-footer'
    | '/edit-homepage'
    | '/healing-journey'
    | '/login'
    | '/signup'
    | '/media'
    | '/other-sections'
    | '/preview'
    | '/subscriptions'
    | '/healing-journey/$slug'
    | '/healing-journey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/damage-journey'
    | '/edit-cards'
    | '/edit-footer'
    | '/edit-homepage'
    | '/login'
    | '/signup'
    | '/media'
    | '/other-sections'
    | '/preview'
    | '/subscriptions'
    | '/healing-journey/$slug'
    | '/healing-journey'
  id:
    | '__root__'
    | '/'
    | '/damage-journey'
    | '/edit-cards'
    | '/edit-footer'
    | '/edit-homepage'
    | '/healing-journey'
    | '/login'
    | '/signup'
    | '/media'
    | '/other-sections'
    | '/preview'
    | '/subscriptions'
    | '/healing-journey/$slug'
    | '/healing-journey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DamageJourneyRoute: typeof DamageJourneyRoute
  EditCardsRoute: typeof EditCardsRoute
  EditFooterRoute: typeof EditFooterRoute
  EditHomepageRoute: typeof EditHomepageRoute
  HealingJourneyRoute: typeof HealingJourneyRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MediaRoute: typeof MediaRoute
  OtherSectionsRoute: typeof OtherSectionsRoute
  PreviewRoute: typeof PreviewRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-sections': {
      id: '/other-sections'
      path: '/other-sections'
      fullPath: '/other-sections'
      preLoaderRoute: typeof OtherSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healing-journey': {
      id: '/healing-journey'
      path: '/healing-journey'
      fullPath: '/healing-journey'
      preLoaderRoute: typeof HealingJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-homepage': {
      id: '/edit-homepage'
      path: '/edit-homepage'
      fullPath: '/edit-homepage'
      preLoaderRoute: typeof EditHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-footer': {
      id: '/edit-footer'
      path: '/edit-footer'
      fullPath: '/edit-footer'
      preLoaderRoute: typeof EditFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-cards': {
      id: '/edit-cards'
      path: '/edit-cards'
      fullPath: '/edit-cards'
      preLoaderRoute: typeof EditCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-journey': {
      id: '/damage-journey'
      path: '/damage-journey'
      fullPath: '/damage-journey'
      preLoaderRoute: typeof DamageJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healing-journey/': {
      id: '/healing-journey/'
      path: '/'
      fullPath: '/healing-journey/'
      preLoaderRoute: typeof HealingJourneyIndexRouteImport
      parentRoute: typeof HealingJourneyRoute
    }
    '/healing-journey/$slug': {
      id: '/healing-journey/$slug'
      path: '/$slug'
      fullPath: '/healing-journey/$slug'
      preLoaderRoute: typeof HealingJourneySlugRouteImport
      parentRoute: typeof HealingJourneyRoute
    }
  }
}

interface HealingJourneyRouteChildren {
  HealingJourneySlugRoute: typeof HealingJourneySlugRoute
  HealingJourneyIndexRoute: typeof HealingJourneyIndexRoute
}

const HealingJourneyRouteChildren: HealingJourneyRouteChildren = {
  HealingJourneySlugRoute: HealingJourneySlugRoute,
  HealingJourneyIndexRoute: HealingJourneyIndexRoute,
}

const HealingJourneyRouteWithChildren = HealingJourneyRoute._addFileChildren(
  HealingJourneyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DamageJourneyRoute: DamageJourneyRoute,
  EditCardsRoute: EditCardsRoute,
  EditFooterRoute: EditFooterRoute,
  EditHomepageRoute: EditHomepageRoute,
  HealingJourneyRoute: HealingJourneyRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MediaRoute: MediaRoute,
  OtherSectionsRoute: OtherSectionsRoute,
  PreviewRoute: PreviewRoute,
  SubscriptionsRoute: SubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
